--- 
- name: Install latest packes
  become: yes
  apt:
    update_cache: yes
    autoremove: yes
    state: present
    pkg:
      - vim
      - python3

- name: Install GPIO
  become: yes
  apt:
    state: present
    pkg:
      - python3-rpi.gpio

- name: Enable Remote GPIO
  become: yes
  shell: raspi-config nonint do_rgpio 0

# Todo: Add global variables
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Set keyboard locale
  become: yes
  shell: raspi-config nonint do_change_locale {{ keyboard.locale }}

- name: Set keyboard locale
  become: yes
  shell: raspi-config nonint do_configure_keyboard {{ keyboard.language }}

