---
- name: Add user {{ user.name }} with proper groups for Raspberry PI to use Sensors
  become: yes
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: /bin/bash
    groups: sudo,spi,i2c,adm
    append: yes

- name: Add SSH authorized key for {{ user.name }} access.
  become: yes
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Disable default pi user
  become: yes
  ansible.builtin.user:
    name: pi
    shell: /usr/bin/nologin
    password_lock: yes